### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for UnetGenerator

### ISSUE THREAD

**Issue by xjhjinhui** [RoyalVane/MMAN#1]
Unexpected running stats buffer(s) "model.U4.2.U3.4.U2.4.U1.23.U0.6.running_mean" and "model.U4.2.U3.4.U2.4.U1.23.U0.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.U4.2.U3.4.U2.4.U1.26.running_mean" and "model.U4.2.U3.4.U2.4.U1.26.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.U4.2.U3.4.U2.7.running_mean" and "model.U4.2.U3.4.U2.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.U4.2.U3.7.running_mean" and "model.U4.2.U3.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.

您好，我在测试训练数据时出现了上面的错误（market1501和LIP数据集均有这个错误），原模型中是训练200次，由于电脑配置较低我只训练了25次，并在which_epoch中改为25次。网上有说是pytorch版本的原因，可我电脑上安装的是0.4.0这个版本，请问我要如何解决这个错误？

**Comment by RoyalVane** [comment]
This code was trained and tested on pytorch 0.3.1 in our experiment. The best way is to retrain your model on 0.3.1. A fallback choice may go to the suggestion "set track_running_stats=True" when intialize the InstanceNorm2d like this: XXX = nn.InstanceNorm2d(track_running_stats=True). But I have not verified this on 0.4.0.

**Comment by xjhjinhui** [comment]
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 28 and 27 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111
`Total number of parameters: 85443960
-----------------------------------------------
model [Pix2PixModel] was created
/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/container.py:67: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
/home/tay/test/MMAN/models/networks.py:628: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return {'GAN':sm(t * 5.0), 'L1':lsm(t)}
/home/tay/test/MMAN/models/networks.py:612: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return {'GAN':sm(t * 5.0), 'L1':lsm(t)}
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model.test()
  File "/home/tay/test/MMAN/models/pix2pix_model.py", line 184, in test
    self.fake_B_GAN_S = self.netG(self.real_A_S)['GAN']
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/test/MMAN/models/networks.py", line 415, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 115, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/test/MMAN/models/networks.py", line 611, in forward
    t = self.U4(x)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/test/MMAN/models/networks.py", line 614, in forward
    return torch.cat([self.con3(x), self.U3(x)], 1)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/test/MMAN/models/networks.py", line 616, in forward
    return torch.cat([self.con2(x), self.U2(x)], 1)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tay/test/MMAN/models/networks.py", line 618, in forward
    return torch.cat([self.con1(x), self.U1(x)], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 28 and 27 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111`

Thanks very much! After changing the pytorch version to 0.3.1, there was no previous error, but a new error was discovered. Some related information on the network told me the input picture size is different (the loading training set has been resize and crop, and it has not been added during the test). I checked the test and train related code and found no errors. A similar problem on the pytorch official [forum](https://discuss.pytorch.org/t/runtimeerror-inconsistent-tensor-sizes-at-pytorch-torch-lib-thc-generic-thctensormath-cu-141-my-data-is-7-7-single-picture-thanks/11893)  said " return torch.cat ([self.con1(x), self.U1(x)], 1)" This dimension is wrong. I'm a beginner and try to solve this problem for a few days.Looking forward to your reply.

**Comment by RoyalVane** [comment]
The reason caused this problem is that the rounding operation is different under diverse system, e.g., int(286/16*16) may not equal to 286.  Please try load_size = 256 in the test commands.

**Comment by xjhjinhui** [comment]
RuntimeError: inconsistent tensor size, expected tensor [256 x 256] and src [3 x 256 x 256] to have the same number of elements, but got 65536 and 196608 elements respectively at /pytorch/torch/lib/TH/generic/THTensorCopy.c:86

Traceback (most recent call last):
  File "test.py", line 23, in <module>
    for i, data in enumerate(dataset):
  File "/home/tay/Royal/MMAN/data/custom_dataset_data_loader.py", line 44, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tay/Royal/MMAN/data/aligned_dataset.py", line 167, in __getitem__
    B = channel_1toN(B, self.opt.output_nc)  # multi channel float tensor   in __getitem__

According to your suggestions,I successfully ran the test program in LIP dataset,but still failed to get the Market1501 segmentation images.In order to test the Market1501 dataset,I have changed the code
`       self.dir_A = os.path.join(opt.dataroot, opt.phase+ '_' + opt.dataset + '_A')
        self.A_paths = sorted(make_dataset(self.dir_A))
        self.dir_B = os.path.join(opt.dataroot, opt.phase+ '_' + opt.dataset + '_B')` into `
        self.dir_A = os.path.join(opt.dataroot, opt.phase + opt.dataset)
        self.A_paths = sorted(make_dataset(self.dir_A))
        self.dir_B = os.path.join(opt.dataroot, opt.phase + opt.dataset)
       `.But the test program still has errors,I found  the two parameter dimensions in the program don't  match,which layer.numpy() is [3 x 256 x 256] and mask.numpy() is [256 x 256].

Under the web page command and without changing your code,I also tried to change the test_LIP_B files same as  the images of test_LIP_A, the errors  were identical.

I tried to change the default parameters of base_options.py these days,like '
dataset_mode->single 
model ->test
init_type->normal (there always NotImplementedError: normalization layer [normal or xavier or kaiming or orthogonalr ] is not found)
 '.
By the way,when I changed the data mode to unaligned,I also modified `self.dir_A = os.path.join(opt.dataroot, opt.phase + 'A')
        self.dir_B = os.path.join(opt.dataroot, opt.phase + 'B')`,because Market dataset doesn't have B images,I just want to get it. 


Could you please give me some advice?I will be deeply appreciated and look forward to your reply.

**Comment by RoyalVane** [comment]
Pretrained models are available now. Please refer to ReadMe.

**Comment by Bo396543018** [comment]
> RuntimeError: inconsistent tensor size, expected tensor [256 x 256] and src [3 x 256 x 256] to have the same number of elements, but got 65536 and 196608 elements respectively at /pytorch/torch/lib/TH/generic/THTensorCopy.c:86
> 
> Traceback (most recent call last):
> File "test.py", line 23, in 
> for i, data in enumerate(dataset):
> File "/home/tay/Royal/MMAN/data/custom_dataset_data_loader.py", line 44, in **iter**
> for i, data in enumerate(self.dataloader):
> File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in **next**
> return self._process_next_batch(batch)
> File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> RuntimeError: Traceback (most recent call last):
> File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/tay/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in 
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/tay/Royal/MMAN/data/aligned_dataset.py", line 167, in **getitem**
> B = channel_1toN(B, self.opt.output_nc) # multi channel float tensor in **getitem**
> 
> According to your suggestions,I successfully ran the test program in LIP dataset,but still failed to get the Market1501 segmentation images.In order to test the Market1501 dataset,I have changed the code
> ` self.dir_A = os.path.join(opt.dataroot, opt.phase+ '_' + opt.dataset + '_A') self.A_paths = sorted(make_dataset(self.dir_A)) self.dir_B = os.path.join(opt.dataroot, opt.phase+ '_' + opt.dataset + '_B')` into `self.dir_A = os.path.join(opt.dataroot, opt.phase + opt.dataset) self.A_paths = sorted(make_dataset(self.dir_A)) self.dir_B = os.path.join(opt.dataroot, opt.phase + opt.dataset)`.But the test program still has errors,I found the two parameter dimensions in the program don't match,which layer.numpy() is [3 x 256 x 256] and mask.numpy() is [256 x 256].
> 
> Under the web page command and without changing your code,I also tried to change the test_LIP_B files same as the images of test_LIP_A, the errors were identical.
> 
> I tried to change the default parameters of base_options.py these days,like '
> dataset_mode->single
> model ->test
> init_type->normal (there always NotImplementedError: normalization layer [normal or xavier or kaiming or orthogonalr ] is not found)
> '.
> By the way,when I changed the data mode to unaligned,I also modified `self.dir_A = os.path.join(opt.dataroot, opt.phase + 'A') self.dir_B = os.path.join(opt.dataroot, opt.phase + 'B')`,because Market dataset doesn't have B images,I just want to get it.
> 
> Could you please give me some advice?I will be deeply appreciated and look forward to your reply.
Hi， I also met this problem when I try to test on market dataset. My solution is to copy LIP mask labels to test_Makert2_B and made it same as LIP'setting.

**Comment by RoyalVane** [comment]
The ground truth labels are not necessary for testing. The only effect of the lack of ground truth is that the IoU can't be calculated. Since the Market dataset doesn't provide the Ground Truth in test_B, you should comment out all the codes about the ''test_B'' when testing on Market. By the way, the aligned mode should NOT be modified in all experiments.
