### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by LDVC124** [RoyalVane/MMAN#11]
Thank you for your reply. My previous problem has been solved. 
    But now I meet a new problem and been stucked: ConnectionRefusedError: [Errno 111] Connection refused. this error occurred after prompt：model [Pix2PixModel] was created.
    Do you have any tips? Be deeply grateful.

**Comment by RoyalVane** [comment]
Have you open the visdom.server before running the training command?

**Comment by LDVC124** [comment]
no, I forgot to open the server. I've learned that. Anyway, thank you for your reply.
