### ISSUE TITLE
test model

### ISSUE THREAD

**Issue by AgnesLily** [RoyalVane/MMAN#13]
What should I do if I want to test this model on a single dataset such as Market, what's parameter should be changed?  
Thanks a lot!

**Comment by AgnesLily** [comment]
Thank you for your great work! Now I can test this  model on my own data.

**Comment by arnabk001** [comment]
@AgnesLily can you please provide me the changes in the code which should be done in order to extract the segmented out region? I want this as a preprocessing step for my work and i'm not able to run this code for my own data

System specs:
python 3.6.6
pytorch 1.0.0
GTX 1060 6GB

Thanks!

**Comment by zhangbin01** [comment]
@AgnesLily 同学你好，请问一下，你是怎么在market上测试的？谢谢！

**Comment by AgnesLily** [comment]
我当时是因为只是想得到一个parsing结果，改他的代码不好改我就没改，测试语句就应该还是他在github上提供的那个。
然后顺着那个test.py看代码发现比较关键的就是需要提供一个B数据，
然后我就复制了A里面相应图片数量的全黑色图片放到B里面（全黑图片的像素大小我忘了，代码里面应该有），然后就有parsing结果了。

**Comment by zhangbin01** [comment]
谢谢了同学！

**Comment by zhangbin01** [comment]
同学，请问你是做什么项目的？也是行人再识别吗？
