### ISSUE TITLE
Error training with PPSS

### ISSUE THREAD

**Issue by Smoltbob** [RoyalVane/MMAN#14]
Training on the PPSS dataset, I get the following errors
`/opt/conda/conda-bld/pytorch_1544202130060/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [225,0,0] Assertion `t >= 0 && t < n_classes` failed.`
Is there anyway to avoid this ?
Thanks

**Comment by Smoltbob** [comment]
The problem was that the PPSS mask images use palette indexes higher than the number of classes. Reordering the palettes fixed the issue.

**Comment by RoyalVane** [comment]
Glad to see that you have solved the problem!
