### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by hammerwy** [RoyalVane/MMAN#6]
Thanks for your excellent work and code.
I have a try to rewrite the code to test some data , but got some issue, 

> RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'

Can you help me solve the problem? or do you have the code for testing single image?

**Comment by RoyalVane** [comment]
In my experience, you might have done some cpu operations on a gpu tensor. Please follow this error hint to modify this gpu tensor "T" by "T.cpu()".
