### ISSUE TITLE
hook values for GAN and L1

### ISSUE THREAD

**Issue by fishman2008** [RoyalVane/MMAN#7]
Could you provide more details regarding the following statements:

#     input_B_GAN: original label image (multiple channels) for GAN loss calculation
#     input_B_L1: original label image (single channel) for L1 loss calculation

Where can I find these details in the paper? Thanks.

**Comment by RoyalVane** [comment]
In pytorch, different losses need different targets in channel numbers. These different hooks are for this aim.
