### ISSUE TITLE
Test on my own data

### ISSUE THREAD

**Issue by wanna2study** [RoyalVane/MMAN#9]
Thanks for your excellent work and code!

I am working on testing the trained model you provide on my own data, but my data only have raw images without groundtruth segementation labels (when test on LIP, the groundtruth segementation labels are offered in the folder ./Human/test_LIP_B), how can I handle this？ Are the groundtruth segementation labels necessary in testing?

I only want to get the segementation results on my data by your trained model without training.

Waiting for you reply and thanks a lot!

**Comment by RoyalVane** [comment]
The ground truth labels are not necessary for testing. The only effect of the lack of ground truth is that the IoU can't be calculated.

**Comment by RoyalVane** [comment]
Since your own dataset doesn't provide the Ground Truth in ''test_B'' folder, you should comment out all the codes about the ''test_B'' when testing on your own dataset.

**Comment by wanna2study** [comment]
Thanks for your reply!

I have alreary run your code on my own data, but there is one more problem:

I find that there are 20 classes for LIP dataset, which is corresponding to the 20 channels in the output parsing results, and you give these 20 classes different colors in 
https://github.com/RoyalVane/MMAN/blob/d4641730a2635affac952b21bce36174a60b5bba/util/util.py#L28

Could you provide the correspondence among the class number and the channel number in output mask results? For example, the background is corresponding to the channel 0.

**Comment by RoyalVane** [comment]
The channel-class correspondence is consistent with the LIP dataset. For Market1501, the visual result implemented in this repo uses the palette ''Market2''.
